version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
      - cache
    environment:
      - DATABASE_URL=postgresql://user:pass@database:5432/testdb
      - REDIS_URL=redis://cache:6379
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=testdb
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:6-alpine
  monitoring:
    image: prom/prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  db_data: